main:
  push:
    - stages:
        - name: sync to github
          image: tencentcom/git-sync
          imports: https://cnb.cool/netcat1/secret/-/blob/main/envs.yml
          settings:
            target_url: https://github.com/netcaty/crx-name2id.git
            auth_type: https
            username: ${GITHUB_USER}
            password: ${GITHUB_TOKEN}